language: c

compiler:
  - gcc
  - clang

env:
  matrix:
    - build_git_twsapi="no"
    - build_git_twsapi="yes"

matrix:
  allow_failures:
    ## as long as handshake features aren't in twsapi
    - build_git_twsapi="no"

before_install:
  - sudo add-apt-repository ppa:hroptatyr/ppa -y
  - sudo apt-get -qq update

install:
  - sudo apt-get install -qq gengetopt
  - sudo apt-get install -qq help2man
  - sudo apt-get install -qq libev-dev
  - sudo apt-get install -qq gperf
  - sudo apt-get install -qq uterus
  - sudo apt-get install -qq libfixc
  - sudo apt-get install -qq unserding
  - sudo apt-get install -qq unsermarkt
  - if test "${build_git_twsapi}" = "yes"; then
      git clone --quiet --depth=100 -b next git://github.com/hroptatyr/twsapi.git ~/builds/twsapi
      && pushd ~/builds/twsapi
      && autoreconf -vfi
      && ./configure --prefix=/usr --enable-shared
      && make
      && sudo make install
      && sudo ldconfig
      && popd
      ;
    else
      sudo apt-get install -qq twsapi
      ;
    fi

before_script:
  - autoreconf -vfi

script:
  - mkdir \=build
  - cd \=build
  - ../configure || (cat config.log; /bin/false)
  - make clean all distcheck V=1

## whitelist
branches:
  only:
    - master
    - next

notifications:
  email:
    - devel@fresse.org
